services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint:
      - /bin/sh
      - -c
      - |
        npm ci --ignore-scripts
        exec "$@"
      - --
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - app_node_modules:/workspace/node_modules
    ports:
      - '4200:4200'
    command: npm run serve
  app-prod:
    profiles: ['production']
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '8080:80'

volumes:
  app_node_modules:
